# Generated by Django 5.2.10 on 2026-05-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="bulk_uploads/"),
        ),
    ]
