# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-05-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0002_bulkupload_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkupload",
            name="gpx_file",
            field=models.FileField(blank=True, null=True, upload_to="bulk_uploads/gpx/"),
        ),
    ]
