# Generated by Django 5.2.10 on 2026-05-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sightings", "0003_bulkupload_gpx_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkupload",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="bulkupload",
            name="gpx_file",
        ),
    ]
