# Generated by Django 5.0.2 on 2024-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesname',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
