# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0002_alter_speciesname_scientific_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inat_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("rank", models.CharField(default="species", max_length=50)),
                ("rank_level", models.FloatField(null=True)),
                ("iconic_taxon_name", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                ("ancestry", models.CharField(blank=True, default="", max_length=500)),
                ("parent_id", models.IntegerField(blank=True, null=True)),
                ("preferred_common_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("observations_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Taxa",
                "ordering": ("preferred_common_name", "name"),
            },
        ),
        migrations.CreateModel(
            name="TaxonName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("lexicon", models.CharField(max_length=100)),
                ("is_valid", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="names", to="species.taxon"
                    ),
                ),
            ],
            options={
                "ordering": ("lexicon", "position"),
            },
        ),
    ]
