# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0003_taxon_taxonname"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="default_photo_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
