# Generated by Django 5.0.2 on 2024-03-06 18:17

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(max_length=4000, null=True)),
                ('is_flagged_as_reported', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ManyToManyField(blank=True, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('upvoted_by', models.ManyToManyField(blank=True, related_name='upvoted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_video', models.BooleanField(default=False)),
                ('file_gcloud_path', models.CharField(max_length=250)),
                ('content_hash', models.CharField(max_length=64)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('textcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialmedia.textcomment')),
                ('title', models.TextField(max_length=80)),
                ('accuracy_ring_radius_meters', models.IntegerField(null=True)),
                ('geoprivacy', models.CharField(choices=[(1, 'public'), (2, 'obfuscated'), (3, 'private')], max_length=16)),
                ('public_location_latitude', models.FloatField()),
                ('public_location_longitude', models.FloatField()),
                ('obfuscation_range_kilometers', models.FloatField()),
                ('obfuscation_box_corner_1_latitude', models.FloatField()),
                ('obfuscation_box_corner_1_longitude', models.FloatField()),
                ('obfuscation_box_corner_2_latitude', models.FloatField()),
                ('obfuscation_box_corner_2_longitude', models.FloatField()),
                ('obfuscation_box_corner_3_latitude', models.FloatField()),
                ('obfuscation_box_corner_3_longitude', models.FloatField()),
                ('obfuscation_box_corner_4_latitude', models.FloatField()),
                ('obfuscation_box_corner_4_longitude', models.FloatField()),
                ('true_location_latitude', models.FloatField()),
                ('true_location_longitude', models.FloatField()),
                ('private_location_latitude', models.FloatField()),
                ('private_location_longitude', models.FloatField()),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_media', to='socialmedia.media')),
                ('replies', models.ManyToManyField(blank=True, related_name='post_replies', to='socialmedia.textcomment')),
            ],
            options={
                'abstract': False,
            },
            bases=('socialmedia.textcomment',),
        ),
    ]
