# Generated by Django 5.0.2 on 2024-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='camera_deployment_date',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='camera_model',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='camera_timestamp_offset_error_details',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='geocoded_location_country',
            field=models.CharField(default='United States', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediapost',
            name='geocoded_location_locality',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='geocoded_location_state',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='geocoded_location_zip_code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='habitat_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='research_use_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='geoprivacy',
            field=models.CharField(choices=[(1, 'public'), (2, 'obscured'), (3, 'private')], max_length=16),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_1_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_1_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_2_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_2_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_3_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_3_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_4_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_box_corner_4_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='obfuscation_range_kilometers',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='private_location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='private_location_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='public_location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='public_location_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='true_location_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='true_location_longitude',
            field=models.FloatField(null=True),
        ),
    ]
