# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_mediapost_camera_deployment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='encounter_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
