# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_mediapost_encounter_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='geocoded_location_country',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
