# Generated by Django 5.0.2 on 2024-03-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_alter_mediapost_geocoded_location_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file_gcloud_path',
            new_name='file_cloud_path',
        ),
    ]
