# Generated by Django 5.0.2 on 2024-04-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_rename_file_gcloud_path_media_file_cloud_path'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.speciesname'),
        ),
    ]
