# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-07-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0007_inappropriatecontentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcomment',
            name='is_flagged_as_reported',
        ),
        migrations.RemoveField(
            model_name='textcomment',
            name='reported_by',
        ),
    ]
