# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-07-01 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_remove_textcomment_is_flagged_as_reported_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inappropriatecontentreport',
            name='reported_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inappropriatecontentreport',
            name='warning_notes',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
