# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_inappropriatecontentreport_reported_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappropriatecontentreport',
            name='warning_notes',
            field=models.CharField(default='', max_length=800),
        ),
    ]
