# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.0.2 on 2024-08-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0010_alter_inappropriatecontentreport_warning_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='research_use_allowed',
        ),
    ]
