# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0011_remove_mediapost_research_use_allowed"),
        ("species", "0003_taxon_taxonname"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_posts",
                to="species.taxon",
            ),
        ),
    ]
