# Generated by Django 5.2.10 on 2026-04-12 02:26

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0012_mediapost_taxon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapost",
            name="sighting_type",
            field=models.CharField(
                choices=[
                    ("live_sighting", "Live Sighting"),
                    ("camera_trap", "Camera Trap or Security Camera"),
                    ("track_sign", "Track or Sign"),
                    ("killed", "Killed"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Type of wildlife sighting",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SightingMedia",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_order", models.PositiveSmallIntegerField(default=1)),
                ("media", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="socialmedia.media")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_media",
                        to="socialmedia.mediapost",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "unique_together": {("post", "media")},
            },
        ),
        migrations.CreateModel(
            name="UserSightingLocation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this location (e.g., 'Backyard', 'North Trail')", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description of the location", max_length=500),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sighting_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["user", "name"], name="socialmedia_user_id_6829a1_idx")],
            },
        ),
    ]
