# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-05-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0013_mediapost_sighting_type_sightingmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='iucn_habitat_lvl1_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='iucn_habitat_lvl1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='iucn_habitat_lvl2_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='iucn_habitat_lvl2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
