# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_expert",
            field=models.BooleanField(
                default=False,
                help_text="Expert user votes directly validate Category, Species and Activity without need for additional consensus",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_volunteer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, verbose_name="Phone Number"),
        ),
        migrations.AddField(
            model_name="user",
            name="warnings",
            field=models.IntegerField(default=0),
        ),
    ]
