# Licensed under the MIT License.
# See LICENSE file in the project root for full license information.

# Generated by Django 5.2.10 on 2026-03-30 19:56

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_warnings_volunteer_expert_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedEmail",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("ban_reason", models.TextField(max_length=2000)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
